### PR TITLE
Pandas update 1.5

### PR DESCRIPTION
**Pull request by xtianpoli**
Based on **dom/pandas-update** branch, it updates the screenshots and temporarily silence the warnings in NBTest.ipynb (while waiting the fix in te next release of ipytablewidgets),

### CODE REVIEW

**Comment by domoritz** [comment]
How do you update the screenshots?

**Comment by domoritz** [comment]
Thank you

**Comment by xtianpoli** [comment]
The Galata test is done by comparing screenshots which can sometimes lead
to false positives (for example, a font has changed as a result of a widget
or library upgrade etc.).

Whenever the test fails (as here
https://github.com/vega/ipyvega/actions/runs/4195915036) the generated
images that differ from the reference images are downloadable in the
Artifact section (at the bottom of the page) in the cell-artifact archive.
If after examination these artifacts are considered to be correct (i.e. the
test failure was a false positive or reference images were missing) they
can be used to update references in  ui-tests/reference-output/screenshots/.

I prefer to update references this way rather than generating them on my
laptop in order to avoid another potential false positive.

NB: The galata configuration provides an option for a greater tolerance in
the comparison of images but I prefer not to use it for the moment.

Le jeu. 16 févr. 2023 à 18:45, Dominik Moritz ***@***.***> a
écrit :

**Comment by domoritz** [comment]
Ah? That's great to know. Can you add a short description to the developer contributing document in this repo so we have this process documented?

**Pull request merged**
