### PR TITLE
Declare ipywidgets as dependency, rather than fail on import

### PR DESCRIPTION
**Pull request by jonringer**
just declare it as a dependency, rather than fail on import.

### CODE REVIEW

**Comment by jonringer** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/78254

**Comment by jakevdp** [comment]
We originally chose to do it this way because ipywidgets is not actually a hard requirement for this package. Is there any reason you can't explicitly install ipywidgets when you need it?

**Comment by jonringer** [comment]
we can, it's just odd to get an import error when running the test suite

**Comment by jakevdp** [comment]
Ah, thanks for po Noting that out. Those tests should be skipped when ipywidgets is not installed.

**Comment by jonringer** [comment]
another option would be to add an extra, so you have `pip install ipyvega[ipywidgets]` or something like that. 

Either way, nixpkgs will be including it into the closure. Thought upstreaming the issue would be the right thing as this is atypical dependency management.

**Comment by jakevdp** [comment]
In my experience this is typical for optional dependencies.

**Comment by jonringer** [comment]
optional dependencies will generally select an alternate code path which won't cause runtime failures. But now I can't remember the conditions in which the tests were calling it, :(

**Pull request closed without merging**
