### PR TITLE
Fix bug specifying altair vegalite version (#101)

### PR DESCRIPTION
**Pull request by polyatail**
Small change, fixes bug.

### CODE REVIEW

**Comment by domoritz** [comment]
See https://github.com/vega/ipyvega/issues/101. Can this be closed?

**Comment by polyatail** [comment]
I'm not sure I understand--is there a version of `altair` that has `altair.vegalite.v3` namespace?

**Comment by domoritz** [comment]
Not yet but there will be soon. I already updated ipyvega to support Vega-Lite 3. If you need support for Vega-Lite 2 9and the current Altair), you can install https://github.com/vega/ipyvega/releases/tag/v1.4.0. Or am I missing something?

**Comment by polyatail** [comment]
That's fine, I get the logic behind updating `ipyvega` to use newer versions of vega/vegalite JS. But it seems a little premature to make this particular change and pin a (pre)release when I don't even see a branch of altair with `vegalite.v3`.

**Comment by jakevdp** [comment]
The work in progress to support vegalite 3 in Altair is here: https://github.com/altair-viz/altair/pull/1249

I've not yet changed the vegalite.v2 entrypoint to vegalite.v3 because I've not gotten that far yet, and it's still unclear when the vega-lite 3 release will be final.

**Comment by domoritz** [comment]
> But it seems a little premature to make this particular change and pin a (pre)release when I don't even see a branch of altair with vegalite.v3

ipyvega exists independently from Altair.

**Comment by polyatail** [comment]
🙄

**Comment by domoritz** [comment]
Thank you for filing the issue and sending the PR! I hope we could clarify why we do things the way we do.

**Pull request closed without merging**
